author:
    email: jrnas@users.noreply.github.com
    homepage: https://github.com/jrnas/wn-smartmeter
    name: jrnas
  description: Wiener Netze Smartmeter
  files:
    - custom_components/wn_smartmeter/__init__.py
    - custom_components/wn_smartmeter/sensor.py
  keywords:
    - wn-smartmeter
    - wien
    - wienernetze
    - smartmeter
    - homeassistant
    - home-assistant
    - custom-component
    - python
  license: MIT License
  name: wienernetzesmartmeter
  type: component